spring.application.name=frete-inteligente
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update

# Mapbox API Token (para cálculo de rotas reais)
mapbox.access-token=pk.eyJ1IjoidGlhZ29ob2xhbmRhIiwiYSI6ImNtaHA0NXhnODBqMTEya3BqNzQ5cmg1czgifQ.NMpdUaZ6DY3fdrvprxP4Nw